# image will be published to ghcr.io/<user>/<name>
name: jany-ublue-kinoite-image
# description will be included in the image's metadata
description: This is my personal Kinoite image, based on ublue

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/kinoite-nvidia
image-version: latest # latest is also supported if you want new updates ASAP

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - type: files
    files:
      - usr: /usr
          # copy static configurations
          #
          # copies config/files/usr into your image's /usr
          #
          # configuration you wish to end up in /etc/ on the booted system
          # should be added into /usr/etc/ as that is the proper "distro"
          # config directory on ostree. Read more in the files module's README

  - type: rpm-ostree
    repos: # - https://copr.fedorainfracloud.org/coprs/atim/starship/repo/fedora-%OS_VERSION%/atim-starship-fedora-%OS_VERSION%.repo
    remove:
      - firefox # default firefox removed in favor of flatpak
      - firefox-langpacks # langpacks needs to also be removed to prevent dependency problems
      - kwrite
      - plasma-discover-notifier

  - type: default-flatpaks
    install:
      - Bottles: com.usebottles.bottles
      - GIMP: org.gimp.GIMP
      - Gwenview: org.kde.gwenview
      - Ktorrent: org.kde.ktorrent
      - Libreoffice: org.libreoffice.LibreOffice
      - Firefox: org.mozilla.firefox
      - Mpv: io.mpv.Mpv
      - Okular: org.kde.okular
      - Olympus: io.github.everestapi.Olympus
      - Prism Launcher: org.prismlauncher.PrismLauncher
      - ProtonVPN: com.protonvpn.www
      - Signal: org.signal.Signal
      - Spotify: com.spotify.Client
      - Steam: com.valvesoftware.Steam
      - Proton-GE: com.valvesoftware.Steam.CompatibilityTool.Proton-GE
      - Teams: com.github.IsmaelMartinez.teams_for_linux
      - Vesktop: dev.vencord.Vesktop
      - Xournalpp: com.github.xournalpp.xournalpp

  - type: script
    scripts:
      # this sets up the proper policy & signing files for signed images to work
      - signing.sh
      
